### PR TITLE
BACK-56

### PR DESCRIPTION
**Pull request by larasodjati**
Created delete single message route.

### CODE REVIEW

**Review by Manizha-khorram — CHANGES_REQUESTED** [review]
Nice work Lara, I tested this in postman. When I delete a message it is deleted for both parties. Do you think we can add some functionality that it could be deleted for both partied just for some period of time like 24 hours and if these much time passed the user just can delete message for herself not for other user!
Also right now every user can delete every other user message in postman which message is not related to. I think we should include a condition to restrict this just for related postedByUser or recievedByUser.

**Comment by larasodjati** [comment]
Hi @Manizha-khorram, well noted, and thank you for the feedback. I thought about my previous mistake and the message deletion concept very carefully, and I think we just need to delete a message from a user who posted it. 

In this case, it will look similar to Slack messages where user can delete their message in every private chat/room but can't delete any partner's/recipient's messages. Only recipient can delete their message by themselves.

The purpose of this concept is when users mistyped or don't think the message is appropriate they can delete it and send a new message to the recipient, but keep the recipient message (history) as it is.

Please let me know what you think about it. I also have pushed the new code for your reference.

**Review by Manizha-khorram — APPROVED** [review]

**Comment by Manizha-khorram** [comment]
> Hi @Manizha-khorram, well noted, and thank you for the feedback. I thought about my previous mistake and the message deletion concept very carefully, and I think we just need to delete a message from a user who posted it.
> 
> In this case, it will look similar to Slack messages where user can delete their message in every private chat/room but can't delete any partner's/recipient's messages. Only recipient can delete their message by themselves.
> 
> The purpose of this concept is when users mistyped or don't think the message is appropriate they can delete it and send a new message to the recipient, but keep the recipient message (history) as it is.
> 
> Please let me know what you think about it. I also have pushed the new code for your reference.

Y

**Comment by Manizha-khorram** [comment]
Lara, it looks reasonable that just posted user wants to delete its messages. Maybe at some point recievedByUser wants to delete some messages just from its history. Not sure it is necessary or not right now!
@jpremo Can you please review, if it is approved from your point of view?
Thanks

**Review by jpremo — APPROVED** [review]

**Pull request merged**
